services:
  initial-challenge:
    image: nginx:latest
    profiles: [init]
    volumes:
      - ./certbot/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./certbot/www/:/var/www/html/:ro
    ports:
      - 80:80

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path /var/www/html --force-renewal --email jenahruby@gmail.com -d decoweb.online --agree-tos
    volumes:
      - ./certbot/www/:/var/www/html/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
