services:
  frontend:
    restart: always
    profiles: [production]
    build:
      context: frontend
      dockerfile: Dockerfile.production
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro

  backend:
    restart: always
    profiles: [production]
    build:
      context: backend
      dockerfile: Dockerfile.production
    volumes:
      - ./backend:/app
    networks:
      - backend

  api:
    image: nginx:latest
    restart: always
    profiles: [production]
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf/:ro
    depends_on:
      - backend
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
