services:
  frontend:
    restart: always
    profiles: [production]
    build:
      context: frontend
      dockerfile: Dockerfile.production
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - frontend
      - certbot
    volumes:
      - ./frontend/nginx.conf.production:/etc/nginx/nginx.conf/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro

  backend:
    restart: always
    profiles: [production]
    build:
      context: backend
      dockerfile: Dockerfile.production
    volumes:
      - ./backend:/app
    networks:
      - backend

  api:
    image: nginx:latest
    restart: always
    profiles: [production]
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf/:ro
    depends_on:
      - backend
    networks:
      - frontend
      - backend

  initial-challenge:
    image: nginx:latest
    profiles: [challenge]
    volumes:
      - ./frontend/nginx.conf.challenge:/etc/nginx/nginx.conf/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - backend
    networks:
      - frontend

  certbot:
    profiles: [challenge, production]
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/certbot --force-renewal --email jenahruby@gmail.com -d decoweb.com --agree-tos
    networks:
      - frontend
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  frontend:
  backend:
