services:
  frontend-dev:
    profiles: [dev]
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    depends_on:
      - backend

  frontend-preview:
    profiles: [preview]
    build:
      context: frontend
      dockerfile: Dockerfile
    command: sh -c "npm run build && npm run preview"
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    profiles: [dev, preview]
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000