services:
  frontend-dev:
    profiles: [dev]
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    depends_on:
      - backend

  frontend-preview:
    profiles: [preview]
    build:
      context: frontend
      dockerfile: Dockerfile.preview
    ports:
      - 5173:5173
    depends_on:
      - backend

  frontend-release:
    profiles: [release]
    image: johnybuk/decoweb:latest
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000