services:
  initial-challenge:
    image: nginx:latest
    profiles: 
      - init
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./www/:/var/www/html/:ro
    ports:
      - 80:80

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path /var/www/html --force-renewal --email jenahruby@gmail.com -d decoweb.online --agree-tos
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/:/etc/letsencrypt/:rw
    profiles: 
      - init  
      - renew

  certbot-dryrun:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path /var/www/html --force-renewal --email jenahruby@gmail.com -d decoweb.online --agree-tos --dry-run
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/:/etc/letsencrypt/:rw
    profiles: 
      - init  
      - dryrun