# Generated by Django 5.1.7 on 2025-04-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_depth', models.IntegerField()),
                ('bottom_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen', models.IntegerField()),
                ('helium', models.IntegerField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoweb.strategy')),
            ],
        ),
    ]
