# Generated by Django 5.1.7 on 2025-05-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='bottom_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='target_depth',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen', models.IntegerField(default=21)),
                ('helium', models.IntegerField(default=0)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoweb.strategy')),
            ],
        ),
        migrations.DeleteModel(
            name='Gass',
        ),
    ]
